### ISSUE TITLE
ncbi/taxonomy:9606 not working

### ISSUE THREAD

**Issue by sarala** [identifiers-org/cloud-ws-resolver#12]
ncbi/taxonomy should list ncbi as the provider. The implementation works for ols/chebi:1234 but not for others eg: pdb

**Comment by mbdebian** [comment]
This is very likely to be a problem with the filter I use in the lambda expression that goes through all the possible resources for a given Compact ID.
I have fixed the code and it will be tested and deployed according to our kanban board ^_^

**Comment by mbdebian** [comment]
This is now fixed in release 1.0.0
