### ISSUE TITLE
Provider code in the resolver output

### ISSUE THREAD

**Issue by sarala** [identifiers-org/cloud-ws-resolver#14]
It would be good to have the provider code in the resolver output.

**Comment by mbdebian** [comment]
Do you mean the 'selector' that corresponds to each resolved resource?

**Comment by sarala** [comment]
Yes, it's just called the provider code in the publication.

**Comment by mbdebian** [comment]
This is a good use case for the redesign of the HQ data backend, providers are an entity themselves, and we could have an endpoint to search for provider information by any of the fields that describe a provider entity.
That way we can make sure that every provider has a 'selector', and also, that the selector can be located for querying the resolver.
All this in addition to having the 'selector' reported in the resolver response as an additional piece of information, let's see the different scenarios:
- You query the service without selector, this means
  - You're after the providers, so you don't need to know the 'selector' in advance.
  - You don't know the 'selector', so you opt for getting all the options and then decide from the client point of view.
- You query the service with 'selector'
  - You know a provider 'selector' in advance and want to lock down the results to only that provider, dealing with HTTP 404 on the client side for those cases where that provider has no data on the given _Compact ID_.
I think it makes sense to include the selector as part of the response from the _Resolver_, to cover the second use case, so you save up one request to a _Provider_ web service to find out what's the 'selector' for the provider you're after.

**Comment by mbdebian** [comment]
The response to a resolution request now includes the provider selector, a.k.a. _resourcePrefix_, as shown in the example:
```json
{
    "apiVersion": "1.0",
    "errorMessage": null,
    "payload": {
        "resolvedResources": [
            {
                "id": "MIR:00100009",
                "resourcePrefix": "ebi",
                "accessUrl": "http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:986456",
                "info": "ChEBI (Chemical Entities of Biological Interest)",
                "institution": "European Bioinformatics Institute, Hinxton, Cambridge",
                "location": "UK",
                "official": true,
                "recommendation": {
                    "recommendationIndex": 99,
                    "recommendationExplanation": "Official resource in this context"
                }
            },
            {
                "id": "MIR:00100158",
                "resourcePrefix": "ols",
                "accessUrl": "http://www.ebi.ac.uk/ols/ontologies/chebi/terms?obo_id=CHEBI:986456",
                "info": "ChEBI through OLS",
                "institution": "European Bioinformatics Institute, Hinxton, Cambridge",
                "location": "UK",
                "official": false,
                "recommendation": {
                    "recommendationIndex": 0,
                    "recommendationExplanation": "This resource is not official within this context"
                }
            },
            {
                "id": "MIR:00100565",
                "resourcePrefix": "bptl",
                "accessUrl": "http://purl.bioontology.org/ontology/CHEBI/CHEBI:986456",
                "info": "ChEBI through BioPortal",
                "institution": "National Center for Biomedical Ontology, Stanford",
                "location": "USA",
                "official": false,
                "recommendation": {
                    "recommendationIndex": 0,
                    "recommendationExplanation": "This resource is not official within this context"
                }
            }
        ]
    }
}
```
