### ISSUE TITLE
feed back from nick

### ISSUE THREAD

**Issue by sarala** [identifiers-org/cloud-ws-resolver#24]
-whats the score that comes with result? probably not needed: ChEBI 
-if I enter a prefix like your example (no provider code) then 'resolve' is misleading - its just search
once you resolve and get to results page, link back does not work, so you need to refresh. so that needs fixing
-provider code does resolve, but going through the results page very briefly
-error detection on what user searches, eg: pdb/rcsb:2gc4 (backwards)

**Comment by sarala** [comment]
- I suggest we change the button labels to 'search' and 'redirect'
- Guess we can take the scores out now but once we have a fancy way of scoring, we can add this information.

**Comment by nsjuty** [comment]
Thanks Sarala for uploading my comments.
To clarify a bit more:
1. search chebi:12345 gives output with a score, which is not explained:
 ChEBI (Chemical Entities of Biological Interest)
http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:12345
European Bioinformatics Institute, Hinxton, Cambridge
Score: 99
UK
- i think that can just be removed (and it seems to be wrong also!)
2. The 'I'm feeling lucky' link doesn't do anything.
3. Prefix registration link does not work
4. The resolve button is misleading, as it will resolve OR give list of results. You could just have 'GO' (tool tip maybe?), and lose the 'feel lucky' button
5. No way to go back once resolution / search is processed. 
6. Error detection/message would be good, as once you press go, the page doesn't do anything, so seems like the button if broken.
